import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import BackButton from '../../components/BackButton';

const PredictedCrop = () => {
  const location = useLocation();
  const { cropPrediction } = location.state || {};
  const navigate = useNavigate();

  if (!cropPrediction) {
    // If no prediction, redirect back to create crop page
    navigate('/crops/create');
  }

  return (
    <div className="flex flex-col items-center justify-center min-h-screen p-4" style={{ backgroundColor: '#013220' }}>
      <h1 className="text-3xl mb-4 text-white text-center">All the crops generated by AI</h1>
      <BackButton destination='/crops/create' />
      <div className="border-2 border-gray-500 p-4 mx-4 rounded-md bg-white max-w-2xl w-full m-auto flex flex-col items-center">
        <h2 className="text-xl mb-4 text-center">Predicted Crops:</h2>
        <p className="text-center">
          Note: The crop predictions provided by this application are generated using the MERN stack combined with AI technology. Please ensure that the results are supervised and validated by an agriculture professional before making any farming decisions.
        </p>
        {/* Display the predicted crops with paragraph spacing */}
        {cropPrediction && cropPrediction.split('\n').map((paragraph, index) => (
          <p key={index} className="mb-4 text-center">{paragraph}</p>
        ))}
      </div>
      <button 
        onClick={() => navigate('/crops/getall')}
        className="mt-4 px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-700"
      >
        Go to Crop Prediction Main Page
      </button>
    </div>
  );
};

export default PredictedCrop;
